openapi: 3.0.1
info:
  title: User Registration API
  version: v1
  description: API endpoint to register a new user and trigger welcome email.

paths:
  /api/v1/users/registrations:
    post:
      tags:
        - User Registration
      summary: Register a new user
      description: Creates a new user account and sends a welcome email.
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user
              properties:
                user:
                  type: object
                  required:
                    - first_name
                    - last_name
                    - phone_number
                    - email
                    - password
                    - password_confirmation
                  properties:
                    first_name:
                      type: string
                      example: John
                    last_name:
                      type: string
                      example: Doe
                    phone_number:
                      type: string
                      example: "3495439988"
                    email:
                      type: string
                      format: email
                      example: john1234.doe@example.com
                    password:
                      type: string
                      format: password
                      example: password123
                    password_confirmation:
                      type: string
                      format: password
                      example: password123
                    avatar:
                      type: string
                      nullable: true
                      example: null
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              example:
                message: Registration successful! Please check your email.
                user:
                  id: 1 
                  first_name: John
                  last_name: Doe
                  phone_number: "3495439988"
                  email: john1234.doe@example.com
                  created_at: "2025-04-18T08:00:00Z"
                  updated_at: "2025-04-18T08:00:00Z"
        '422':
          description: Validation errors
          content:
            application/json:
              example:
                errors:
                  - Email has already been taken
                  - Password confirmation doesn't match Password
        '500':
          description: Internal server error
          content:
            application/json:
              example:
                error: "Unexpected error occurred"
