default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: Amar_Gupta
  password: Admin@123
  host: localhost

development:
  <<: *default
  database: auth2

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>